# Generated by Django 5.1.3 on 2024-11-11 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='название датчика')),
                ('description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='описание датчика')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='температура')),
                ('date_of_measurement', models.DateTimeField(auto_now_add=True, verbose_name='дата и время измерения')),
                ('sensors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors_inf', to='measurement.sensor')),
            ],
        ),
    ]
