# Generated by Django 5.1.3 on 2024-11-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.CharField(blank=True, default='text', max_length=2000, verbose_name='описание датчика'),
            preserve_default=False,
        ),
    ]
